### ISSUE TITLE
Use valid identifiers for modules

### ISSUE THREAD

**Issue by danse** [danse/setup_requirements#3]
Using this module, when a script is created with setuptools entry points, the script start will fail, because the requirements.txt file into egg info will contain random generated module identifiers.

Traceback (most recent call last):
  File "... bin/granpa", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: 361544

 A solution would be to use module identifiers corresponding to module names, but the default behavior for pip is to search first the pypi, so the provided url could be ignored.

**Comment by danse** [comment]
I don't remember the specific issue, but i believe that now there are better ways to provide a custom source for a package. Maybe the whole project could be archived or deleted
